# Projects endpoints
@BASE_URL = http://localhost:3001
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3Njk5MDU3NjMsImV4cCI6MTc2OTk5MjE2M30.XJWbBq4FJ1t6IQ5YfDaSRNF4SjBOHSVXeADRlBtfrYw
@PROJECT_ID = 3fee839a-9d8b-42e4-aeed-e2862648066c
### List projects
GET {{BASE_URL}}/api/projects?page=1&filter=
Authorization: Bearer {{TOKEN}}

### Create project
POST {{BASE_URL}}/api/projects
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "My Test Project",
  "description": "Created via REST Client",
  "theme": "default",
  "primary": "#ff0000",
  "secondary": "#00ff00",
  "tertiary": "#0000ff"
}

### Get project by id
GET {{BASE_URL}}/api/projects/{{PROJECT_ID}}/open
Authorization: Bearer {{TOKEN}}

### Update project
PUT {{BASE_URL}}/api/projects/{{PROJECT_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Updated Project Name",
  "description": "Updated via REST Client",
  "theme": "default",
  "primary": "#111111",
  "secondary": "#00ff00",
  "tertiary": "#0000ff"
}

### Delete project
DELETE {{BASE_URL}}/api/projects/{{PROJECT_ID}}
Authorization: Bearer {{TOKEN}}

### Get project style
GET {{BASE_URL}}/api/projects/{{PROJECT_ID}}/style
